### ISSUE TITLE
Add team pages

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/insights.ubuntu.com#10]
Build hard coded team pages that filter the posts by the team tag and feature posts with hidden tags such as "_maas-team". Hide underscore tags from the frontend.

Teams:
- MAAS
- Snappy
- JAAS
- Landscape
- LXD
- Design?

**Comment by pmahnke** [comment]
Juju? Juju and Jaas?
Server team
Kernel team
... perhaps more

**Comment by anthonydillon** [comment]
This has been done.
