### ISSUE TITLE
Webinars images are squashed on homepage

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/insights.ubuntu.com#102]
We need to allow them to fit by constraining just height or width.

Might want to try another layout as well, perhaps a matrix, or card?

**Comment by frankiegranato** [comment]
This issue is related to related to https://github.com/canonical-websites/insights.ubuntu.com/pull/97

**Comment by frankiegranato** [comment]
@anthonydillon can you add an estimate this please? I'd guess something like an 8.

**Comment by anthonydillon** [comment]
@frankiegranato thanks, its an easy tweak. I have filled an issue on the pattern in Vanilla for this already.
