### ISSUE TITLE
Build: missing bits from press-centre

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#113]
Add “Follow us” section (frankie)
Add “Downloads” section (frankie) [link to design site]
Add “About” section (frankie) [link to canonical site]
See copydoc that Frankie is working on

**Comment by shivjoshi1996** [comment]
Hi @anthonydillon could you estimate this please

**Comment by frankiegranato** [comment]
Follow this copy doc please: insights.ubuntu.com/press-centre/ - copy doc (vanilla insights) https://docs.google.com/document/d/1liiT3l86LHfIyYd_Neg5LAAMRa44VF5QlF63S2gph3Q/edit#

**Comment by anthonydillon** [comment]
Peter did this 🎉
