### ISSUE TITLE
Consistent 500 error for “Meltdown, Spectre and Ubuntu” article on staging

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/insights.ubuntu.com#116]
For both @frankiegranato and me, [staging’s version of the “Meltdown, Spectre, and Ubuntu” article](https://insights.staging.ubuntu.com/2018/01/24/meltdown-spectre-and-ubuntu-what-you-need-to-know/)  consistently returns a “500: Server error”.

[The same article on insights.ubuntu.com](https://insights.ubuntu.com/2018/01/24/meltdown-spectre-and-ubuntu-what-you-need-to-know/) works fine, and other articles on staging also work fine.

**Comment by frankiegranato** [comment]
This is still happening: 
![screen shot 2018-01-29 at 13 42 01](https://user-images.githubusercontent.com/17002826/35513235-48d2f182-04fa-11e8-81b0-c506b1987b24.png)
Hopefully we'll tackle this bug in the Insights workshop tomorrow.
