### ISSUE TITLE
Update styling on pagination

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/insights.ubuntu.com#118]
Could you estimate this please? Cheers @anthonydillon

**Comment by pmahnke** [comment]
https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/

you can use: 

- per_page=5
- page=4 or offset=15

on the posts api and the X-WP-Total header for total number ...

as an MVP, could we just do a 'load more' or 'next' and 'previous' page to start?
