### ISSUE TITLE
The link is too illegible on topic pages

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#157]
On topic pages, the cta link is too illegible on the dark background. See screenshots for examples: 
![Screen Shot 2018-02-01 at 13.44.11.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/1982cb6a-a9cd-4a58-998a-d318e2bd75cd)
![Screen Shot 2018-02-01 at 13.43.47.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/834953c5-985b-44bb-8495-e1790d70fec3)![Screen Shot 2018-02-01 at 13.43.59.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/cf8c4292-0fa6-4c97-bdfe-5164584fc0dc)

@spencerbygraves @anthonydillon Can we use some better-constrasting colours please? We definitely can not go live like this.

**Comment by spencerbygraves** [comment]
@frankiegranato @anthonydillon Let's use the inverted style

**Comment by anthonydillon** [comment]
@pmahnke did you do this?

**Comment by pmahnke** [comment]
I don't see this... there is code to invert it.

![image](https://user-images.githubusercontent.com/441217/35706537-0505f70a-079e-11e8-9988-1a3ed3dd29cf.png)

**Comment by anthonydillon** [comment]
This has been done.
