### ISSUE TITLE
Add archives to group pages

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/insights.ubuntu.com#159]
They exist, but aren't hooked in... perhaps in the under banner tabs... or footer?

**Comment by frankiegranato** [comment]
Yes, lets make it the last item in the tab menu.

**Comment by frankiegranato** [comment]
I need to work out a way to do this. Although they are accessable via search and via pagination.

**Comment by frankiegranato** [comment]
@steverydz  Sorry to add this task in mid-iteration. If you think it sounds doable, then please do, but if its too much work or if its more complicated than expected, it is totally fine to leave it until next iteration :-)
Lets talk about how this would work (I mean the UX of it).

**Comment by steverydz** [comment]
Pull request: https://github.com/canonical-websites/insights.ubuntu.com/pull/262

@frankiegranato I've added the archives link to the footer but not sure if there is anything else required for this ticket?
