### ISSUE TITLE
Fix display of Facebook icon / broken article header layout

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/insights.ubuntu.com#173]
![Screen Shot 2018-02-02 at 11.53.37.png](https://images.zenhubusercontent.com/593a9cb351aa2c30578108ce/a77d02af-b912-4962-8078-5574b49819d0)

**Comment by WillMoggridge** [comment]
I think I found what looks like another example of this at `/2017/10/05/maas-2-3-0-beta-1-released`
