### ISSUE TITLE
Fix links in Snapd 2.0.10: new media interfaces, channel switching post

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/insights.ubuntu.com#177]
In 'General' paragraph a link to changelog 404s
Link to 'Original article' 404s
 Snapcraft mailing list links to a notification page, see here:
![Screen Shot 2018-02-02 at 12.07.55.png](https://images.zenhubusercontent.com/593a9cb351aa2c30578108ce/d60b9fcc-2d2b-4659-a3d0-b93211f12a64)

**Comment by anthonydillon** [comment]
This is a content issue. Not a platform issue.
