### ISSUE TITLE
Continuing Insights development

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#19]
Alexia's brief: https://docs.google.com/document/d/1Vr1ihPq8EsP1ykjIHrB0caOt2hwPiOZ39kiC2Mr7mP0/edit?ts=59d4c028#heading=h.meo0azuz09li

**Comment by frankiegranato** [comment]
@anthonydillon Are you going to have capacity to work on this during this current iteration?

**Comment by anthonydillon** [comment]
Yea, why not :) I'll get it done.
