### ISSUE TITLE
Missing video's from post meets data

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/insights.ubuntu.com#196]
Posts that have there videos set by customs fields are not displayed. For example:
https://insights.staging.ubuntu.com/2012/11/29/ubuntu-bitnami

**Comment by anthonydillon** [comment]
Either add custom field video to the feed or add the video to the content.

**Comment by Caleb-Ellis** [comment]
Ready for review: https://code.launchpad.net/~caleb-ellis/resource-centre/remove-youtube-metabox/+merge/337775

**Comment by anthonydillon** [comment]
Reviewed and ready to be merged. You will then need to create an RT to have the theme updated on live.
