### ISSUE TITLE
Empty pages look a bit naff

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/insights.ubuntu.com#210]
E.g. see: desktop webinars - no results. Or search for "dfghhhh".

There should probably be a message when there are no articles returned.

**Comment by anthonydillon** [comment]
This issue is part complete by removing the option to filter by types that have no content. This change will be live shortly. 

We could improve the empty search results page.

**Comment by steverydz** [comment]
Fixed by https://app.zenhub.com/workspace/o/canonical-websites/insights.ubuntu.com/issues/243

**Comment by nottrobin** [comment]
@steverydz could you try to put "github.com" links rather than "app.zenhub.com" links in issues? The latter isn't very community-friendly.

In this case that would simply be #243, right?

**Comment by steverydz** [comment]
@nottrobin Sure, I've updated this one.
