### ISSUE TITLE
The cross in the search field does not clear

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/insights.ubuntu.com#212]
When you type in the search field a cross appears but nothing happens when you click the cross. I expect it to clear the text.

**Comment by steverydz** [comment]
Is there a specific browser this is happening in? I've tested in Chrome and Firefox on Ubuntu 17.10 and it is working.

**Comment by steverydz** [comment]
Occurs on this page: https://insights.ubuntu.com/search?q=hello
