### ISSUE TITLE
Add "news" as a filter type

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#220]
Rebecca Cradick is asking if we can add "news" to the filter drop downs (both in page and under the primary nav bar) on Insights. Is this something we can do easily? If so, lets do it. 
I realise that the filterable content is the type (ie. news) and not the category (ie. Canonical announcements)

**Comment by anthonydillon** [comment]
I am not sure it makes much sense to filter by news when there are no group news? News or Canonical announcements are stand alone content types. For example, filtering cloud and server by news would result in no posts.

**Comment by frankiegranato** [comment]
@anthonydillon I believe there are news posts inside the category groups. 
Eg: https://insights.staging.ubuntu.com/desktop?category=news

However, IoT doesn't have any news. But maybe that is ok. Other categories return zero filtered results, don't they? 
https://insights.staging.ubuntu.com/IoT?category=news

**Comment by anthonydillon** [comment]
@frankiegranato Nice, lets add it!
