### ISSUE TITLE
"Related Posts" section of the webpage

### ISSUE THREAD

**Issue by gkatom** [canonical-websites/insights.ubuntu.com#233]
At the end of the post. For example "Your first robot: Introduction to the Robot Operating System [2/5]" , the webpage has a section for "Related Posts" which show me links to the same post or the one before (i.e [1/5]). Ideally, it should be pointing to the [3/5] page for me to smoothly continue the tutorials. Hopefully that can be fixed. Thanks! 

[Source Link](https://insights.ubuntu.com/2018/01/21/your-first-robot-introduction-to-the-robot-operating-system-2-5)

**Comment by anthonydillon** [comment]
I wonder if this was due to the posts not being available yet. I get 3/5, 4/5 and 5/5 is the related posts section.
