### ISSUE TITLE
Link to ubuntu.com in the navbar is not working

### ISSUE THREAD

**Issue by campbieil** [canonical-websites/insights.ubuntu.com#235]
Try to click on ubuntu.com, it doesn't go there on chrome.

**Comment by anthonydillon** [comment]
Thank you very much for reporting this issue. It has been triaged and will be actioned soon.

We need to update the global navigation dependency to the latest version.

**Comment by steverydz** [comment]
Related PRs:

https://github.com/canonical-websites/insights.ubuntu.com/pull/269
https://github.com/canonical-websites/www.ubuntu.com/pull/2842
https://github.com/canonical-websites/www.canonical.com/pull/249
https://github.com/canonical-websites/design.ubuntu.com/pull/110
https://github.com/canonical-websites/jp.ubuntu.com/pull/33
https://github.com/canonical-websites/cn.ubuntu.com/pull/191
