### ISSUE TITLE
Add pagination to homepage

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#238]

**Comment by frankiegranato** [comment]
Currently pagination appears on all pages except the homepage (this was to avoid the unsightly and confusing effect of having pagination appear sandwiched in between the brightalk webinars and the rest of the searchable content).  However, Sarah D has requested this change specifically so lets be accommodating :-)

**Comment by steverydz** [comment]
Pull request: https://github.com/canonical-websites/insights.ubuntu.com/pull/257
