### ISSUE TITLE
Redesign homepage

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#239]

**Comment by frankiegranato** [comment]
Sarah D has requested the following considerations: 
- Shallower hero section (to allow for more content above the fold)
- A newsletter signup on the homepage

From our side, we should remember that 
- the current graphic was just a place holder
- And it might be worth exploring an option where the featured article becomes the main hero.

**Comment by frankiegranato** [comment]
We could also consider ways to promote webinar events

**Comment by anasereijo** [comment]
![insights hp signupcard](https://user-images.githubusercontent.com/36884067/37701665-bf404b66-2ce7-11e8-94fb-023907897e76.jpg)
![insights hp accordion closed](https://user-images.githubusercontent.com/36884067/37701667-c28c9d1a-2ce7-11e8-9513-fa325e904ae2.jpg)
![insights hp accordion open](https://user-images.githubusercontent.com/36884067/37701668-c2a4fd24-2ce7-11e8-9e3b-5d4d8a9bb5c6.jpg)

**Comment by anasereijo** [comment]
@spencerbygraves see attached the latest versions of insights homepage. We are going to A/B test having the accordion and the signup card.

**Comment by spencerbygraves** [comment]
Thanks @anasereijo. Looks good. I don't think we need the grey background behind the featured cards in your first version. Thanks.

**Comment by anasereijo** [comment]
Thank you @spencerbygraves I updated that version.

![insights hp accordion open](https://user-images.githubusercontent.com/36884067/37705660-b2e7a0b4-2cf4-11e8-969b-36288eb6a6fe.jpg)
![insights hp accordion closed](https://user-images.githubusercontent.com/36884067/37705661-b31cd4dc-2cf4-11e8-9918-84d073b4d6bd.jpg)
![insights hp signupcard](https://user-images.githubusercontent.com/36884067/37705663-b337812e-2cf4-11e8-94ac-4f91267793ee.jpg)

**Comment by anasereijo** [comment]
@steverydz final designs attached here. We are going to A/B test both options for signup form. Would be great if you can have a look so tomorrow we can talk through the process/requirements. Any questions I am on IRC. Thanks!

**Comment by steverydz** [comment]
@anasereijo These all look great. Is there any reason why there are only 5 webinars rather than 6?

**Comment by anasereijo** [comment]
@steverydz that's just a screen grab we will not change that section for now. 

Things we need to change:
1. Hero section (title with the wallpaper and 3 featured posts)
2. Signup form - A/B test
- signup form as a card in 3rd position (top row)
- signup form as accordion 

(check the live site [https://insights.ubuntu.com/])

**Comment by anasereijo** [comment]
![insights hp accordion closed](https://user-images.githubusercontent.com/36884067/37828732-580490fc-2e94-11e8-82de-d66ed5ec1424.jpg)
![insights hp accordion open](https://user-images.githubusercontent.com/36884067/37828733-5818c036-2e94-11e8-9825-41673901d568.jpg)
![insights hp signupcard](https://user-images.githubusercontent.com/36884067/37828735-582d2422-2e94-11e8-8143-a8e5fdfadbde.jpg)
