### ISSUE TITLE
Replace press-centre photo

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#241]

**Comment by frankiegranato** [comment]
@anasereijo has supplied a revised version of the photo (with no lenovo logo) here: https://assets.ubuntu.com/v1/dc337e68-image-partners.jpg
Please replace the current version with this one.

**Comment by steverydz** [comment]
Pull request: https://github.com/canonical-websites/insights.ubuntu.com/pull/252
