### ISSUE TITLE
Add 'Media Contacts' to press-centre

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#242]

**Comment by frankiegranato** [comment]
Please add a new right-rail box (positioned in between the 'Follow Us' and 'Archives' boxes) to contain the following information:

Media Contacts

General media enquiries 
pr@canonical.com 

Cloud (UK) 
Canonical@berkeley.global

IoT & Desktop (UK)
3MZCanonical@3monkeyszeno.com 

Cloud & IoT (US)
Canonical@offleashpr.com 

All other enquiries
Contact Canonical [link to: www.ubuntu.com/contact-us]

(A combination of h4 headings and muted headings might work, but please do seek design advice from me or @anasereijo)

**Comment by steverydz** [comment]
Pull request: https://github.com/canonical-websites/insights.ubuntu.com/pull/250
