### ISSUE TITLE
Improve content on an 'empty' category page 

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#243]

**Comment by frankiegranato** [comment]
Perhaps we should include a message ... something like: 

We’ve found 0 results for “white-papers” in the IoT category. 

I'm not sure. Can we have a huddle about this please? @anthonydillon

**Comment by frankiegranato** [comment]
As discussed  - @steverydz  can we remove the empty categories from  the drop down? I will let you know which groups to remove.

**Comment by frankiegranato** [comment]
@steverydz                        
These 3 categories are empty so lets remove them from the menus (both drop downs and filters):
/internet-of-things?category=videos
/internet-of-things?category=white-papers
/desktop?category=webinars

**Comment by steverydz** [comment]
Pull request: https://github.com/canonical-websites/insights.ubuntu.com/pull/259
