### ISSUE TITLE
Error in "Feature article" selection

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#244]
Sarah D recently posted an article titled "An intro to ONLYOFFICE – now available as a snap". She did not intend for this article to become a "Featured Article" but it is appearing as one at the moment (fri 9th march). Is is not clear why this has happened. Sarah is sure she didn't select any options that would imply that this would happen. Lets solve the mystery! What fun.

**Comment by frankiegranato** [comment]
Fyi This issue could be linked to the problem that @pmahnke identified on the ubuntu.com homepage regarding incorrect "spotlight"  articles. Discuss @pmahnke.

**Comment by pmahnke** [comment]
![image.png](https://images.zenhubusercontent.com/591f0a5d51aa2c30577eca63/eee297fe-e483-430f-92f3-cd00d22e320b)

here is the sticky button
