### ISSUE TITLE
Build updated hero section

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/insights.ubuntu.com#253]

**Comment by anthonydillon** [comment]
This there a design or more information for this work? There is no dependent issue.

**Comment by kasiag** [comment]
@anasereijo can you link to the latest design please

**Comment by anasereijo** [comment]
@kasiag @anthonydillon design attached.
![insights hp signupcard](https://user-images.githubusercontent.com/36884067/37827887-26396c58-2e91-11e8-8ebb-5369863c86cd.jpg)

**Comment by anasereijo** [comment]
@steverydz background image here:
https://assets.ubuntu.com/v1/75a98fa8-18.04_beaver_wp_8192x4608_no-BB_AW.jpg

**Comment by anasereijo** [comment]
@steverydz there's a couple of changes on this design:

- we are not using the suru banner any more;
- make the title a h2 instead of h1

see below:
![insights hp accordion](https://user-images.githubusercontent.com/36884067/37914967-597ed5ea-3110-11e8-97ba-4abdb22025bc.jpg)

**Comment by shivjoshi1996** [comment]
This section has been completed, remaining work is tracked in #254
