### ISSUE TITLE
Build two versions of newsletter sign-ups and setup AB test

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/insights.ubuntu.com#254]
- either build 1 page with js to show either version or 2 pages
- setup goal in GA
- setup test in Google optomise
- add Google optomise GTM tracker to u.c pages

**Comment by kasiag** [comment]
@anasereijo can you link to latest design please?

**Comment by anasereijo** [comment]
@kasiag @steverydz  both designs attached
![insights hp accordion closed](https://user-images.githubusercontent.com/36884067/37827913-399ba9f0-2e91-11e8-8afe-700c6038f7a6.jpg)
![insights hp accordion open](https://user-images.githubusercontent.com/36884067/37827914-39af3754-2e91-11e8-909a-7b2abe78509b.jpg)
![insights hp signupcard](https://user-images.githubusercontent.com/36884067/37827915-39c30ee6-2e91-11e8-82df-b2f495af315e.jpg)

**Comment by anasereijo** [comment]
![insights hp accordion open](https://user-images.githubusercontent.com/36884067/37915538-a978fd72-3111-11e8-8d07-f0db8580e101.jpg)
![insights hp accordion closed](https://user-images.githubusercontent.com/36884067/37915539-a98d1b86-3111-11e8-80a0-3049a0a58086.jpg)
![insights hp signupcard](https://user-images.githubusercontent.com/36884067/37915540-a9a2bb12-3111-11e8-82e2-01683913baf1.jpg)
