### ISSUE TITLE
Set the feature image of a post as the OG image for searching

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/insights.ubuntu.com#283]
We currently have no OG (social data) in the header of the site. It would be good to add them.

**Comment by steverydz** [comment]
Note: This will need a default image in case of no featured image being applied

**Comment by steverydz** [comment]
@anasereijo Could you please add the default image we just discussed to this ticket? Thanks :)

**Comment by anasereijo** [comment]
@spencerbygraves we need a generic image for Facebook posts to use when there's no image attached to the articles/webinars. I created the one bellow, please let me know your thoughts. Thanks

![facebook post image](https://user-images.githubusercontent.com/36884067/37898718-7304f5a0-30e1-11e8-8bdf-82251efd52e8.jpg)

**Comment by spencerbygraves** [comment]
Thanks @anasereijo, can you let me know the size that this image please, we'll get Tom to have a look and make the spacing correct.

**Comment by anasereijo** [comment]
@spencerbygraves the size is 1920x1080 thanks

**Comment by spencerbygraves** [comment]
@steverydz @anasereijo here's the version from Tom to use. Thanks.

![ubuntu_insights_facebook_1920x1080](https://user-images.githubusercontent.com/9105999/38018856-02eda0bc-326e-11e8-872e-0b6d5ddb990b.jpg)
