### ISSUE TITLE
Remove the Brighttalk webinars section and feeds - build

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#289]
As we already show the insights webinars as a content type. We should remove the Brighttalk feed section and just use insights content. 

Work items:
- Email Marketing informing them of the date of the switch (they need to add the webinar content from Brighttalk into insights)
- Remove the webinar section at the bottom of the homepage

**Comment by anthonydillon** [comment]
Is there anything for us to do if the editor is just creating a article that matches the brighttalk content?

**Comment by frankiegranato** [comment]
@anthonydillon I would like to get rid of the weird 'second group' of webinars listings on the homepage so it would be nice if these existing Brighttalk webinars could be integrated into the rest of the searchable content. Is that a very annoying job for us to do? Is yes, then lets ask Marketing to do it (if they care). In any case lets delete the weird second grouping from the homepage please. 
Also, I see that authors can already post content that appears as a Webinar so we obviously don't need to do anything in that respect.

**Comment by anthonydillon** [comment]
I thought the plan was for marketing to post the webinars as insights posts with a link to brighttalk? Therefore, the only work we have to do is remove the brighttalk section and just use insights add is.

**Comment by pmahnke** [comment]
@anthonydillon that is the plan, but we need marketing to a) do that work b) put the new homepage live wher they can promote the webinars.

**Comment by anthonydillon** [comment]
Thanks, thought that was it.

**Comment by frankiegranato** [comment]
I just want to be sure we delete the second grouping of webinars from the bottom of the homepage please :-)
@anthonydillon

**Comment by anthonydillon** [comment]
The reason I asked it the title of this issue is automatically resolved once we are just using insights posts for webinars. Should this issue be renamed or is there already cards for removing the brighttalk feed?

**Comment by frankiegranato** [comment]
@anthonydillon I don't follow you. There are no other cards aside from this one. How can we name the issue (or epic?) in a more descriptive way?

**Comment by anthonydillon** [comment]
I updated the title of this issue to reflect the work to be done.
