### ISSUE TITLE
New social media placeholder thumbnail for ubuntu blog

### ISSUE THREAD

**Issue by steverydz** [canonical-websites/insights.ubuntu.com#323]
insights.ubuntu.com is being renamed to blog.ubuntu.com

Currently there is a default social media thumbnail with the insights logo:
![social media placeholder](https://assets.ubuntu.com/v1/33a3ce22-38018856-02eda0bc-326e-11e8-872e-0b6d5ddb990b.jpg)

This needs to be updated to have the new 'blog' logo

**Comment by anasereijo** [comment]
@steverydz here you go: https://assets.ubuntu.com/v1/55a39964-ubuntublog-facebook.png
