### ISSUE TITLE
Headlines are not aligning

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#328]
Why aren't the headlines aligning on the Insights homepage. They were designed to be in alignment even if image size differs. Please investigate.

**Comment by frankiegranato** [comment]
See screen shot 
![ubuntu insights alignment](https://user-images.githubusercontent.com/17002826/39421798-9a7d0766-4c62-11e8-94ac-2a787a139cc5.png)

**Comment by anasereijo** [comment]
@frankiegranato I think it's because the image has a white top and bottom margin.

<img width="338" alt="screen shot 2018-04-30 at 10 39 19" src="https://user-images.githubusercontent.com/36884067/39421838-cefd40f0-4c62-11e8-8582-5578e2ed6548.png">

**Comment by frankiegranato** [comment]
Thank you @anasereijo. It looks like that particular problem can be solved easily. 
But maybe I'm wrong about us designing the system so that the baselines of headlines would always align even is the image size differs. I thought we had enforced a depth of image maximum. But maybe I'm wrong? See screen shot.                       
 ![Ubuntu Insights image alignment.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/32754182-a8c7-4dda-ac70-ce357fa7d119)

**Comment by frankiegranato** [comment]
Do we do something differently on www.ubuntu.com/resources? ![Resources   Ubuntu alignment 02.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/a548846d-b0c6-4c7a-89fc-c9e439c41489)

**Comment by pmahnke** [comment]
@frankiegranato no, see this

![image](https://user-images.githubusercontent.com/441217/39427397-d8bb22a8-4c83-11e8-9a8d-635c95fbfb79.png)


however, you could set a min-height on the image, but where would you set it?  that would get you what you want height-wise, but it might mess up the widths?

worth playing with

**Comment by frankiegranato** [comment]
@steverydz   can we force (encourage) authors to only upload images of a certain aspect ratio? Possibly via a warning or an error message if an ill-fitting image is uploaded?

**Comment by steverydz** [comment]
@frankiegranato We don't have control over what is uploaded, that is handled by WordPress. What we can do is crop or resize in the browser which will make the images look a bit odd if they haven't been uploaded at the correct ratio - which I guess would encourage people to upload the correct ratio images. Is that something you'd like us to try?

**Comment by anthonydillon** [comment]
@steverydz Yes, I think we should hard set a width and height and have the overflow cropped.

**Comment by frankiegranato** [comment]
Agree that we should hard set a width and height and have the overflow cropped.
