### ISSUE TITLE
Include RSS feed from Brighttalk

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#34]
Marketing would like to create an RSS feed that sends new webinars from BrightTalk directly to Insights. By doing this, the marketing team will only need to post a new webinar to one site (ie. BrightTalk) and it will automatically appear on Insights as well.

**Comment by deadlight** [comment]
Feed:
https://www.brighttalk.com/channel/6793/feed/rss

**Comment by frankiegranato** [comment]
@WillMoggridge can you please help @deadlight to figure this one out. If its too tricky then please pass it on to @grahambancroft.
