### ISSUE TITLE
Create Team landing pages - design

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#39]
Design the visual elements to denote "team" pages. Marketing have requested that we create landing pages for more specific categories  (aka team pages). For example the 'Maas' landing page would show only Maas-tagged content.
Marketing would also like the visitor to be able to filter results by month and year.

**Comment by anthonydillon** [comment]
@frankiegranato is this being worked on?

**Comment by frankiegranato** [comment]
The team pages (aka topic pages) are designed and signed off (as far as I"m concerned). So I'm going to close this issue. 

It should be noted however, that the design for the category pages is still in progress. We reviewed the proposed designs (the ones with the photos in the top) today in the Suru Workshop and, and the brand squad have a task to look at "Use of photography & photography guidelines" which will inform this work.
