### ISSUE TITLE
Insight demo - various snags

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#4]
"Featured" spot is missing on homepage

I would recommend making the […] on homepage clickable. But this is a low priority enhancement. 

Date-of-posting is missing from post listings on homepage.

"Upcoming events" is missing from homepage - but maybe this is okay because we rarely have events anyway.  

In article, the date-of-posting is missing.

Side nav is missing - site wide.

RTP will need to be re-integrated site wide. Not sure how yet. 

See separate issue for press centre snags.

**Comment by anthonydillon** [comment]
@frankiegranato thank you for these issues. I have split and triaged all the issues into there own pieces of work.
