### ISSUE TITLE
Write Dockerfile to generate production image for release

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/insights.ubuntu.com#41]

**Comment by tbille** [comment]
This has been done by @WillMoggridge :
https://github.com/canonical-websites/insights.ubuntu.com/commit/ddfe94da9a8c3b007004022274e5638d6f3c4476

Can we confirm that we don't need anything else in that Dockerfile @nottrobin @WillMoggridge?

And I add this task for this issue:
- [ ] Push image to docker hub

**Comment by nottrobin** [comment]
@tbille I haven't included "push image to docker hub" because that should be done by the jenkins job, and so is really part of https://github.com/canonical-websites/insights.ubuntu.com/issues/43

**Comment by nottrobin** [comment]
The only change I'd like to the existing Dockerfile is for [the commit_id section](https://github.com/canonical-websites/insights.ubuntu.com/blob/master/Dockerfile#L11) to look more like [the www.ubuntu.com one](https://github.com/canonical-websites/www.ubuntu.com/blob/master/Dockerfile#L11) - that is:

- Call the build argument "COMMIT_ID" rather than "commit_id"
- Fail if the argument is missing

**Comment by nottrobin** [comment]
Oh also, the repo should have a `.dockerignore` file, along the lines of [the one in docs.ubuntu.com](https://github.com/canonical-websites/docs.ubuntu.com/blob/master/.dockerignore).

**Comment by WillMoggridge** [comment]
This is done now
