### ISSUE TITLE
Create Jenkins jobs to deploy to staging & production, and deploy to the environments

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/insights.ubuntu.com#43]

**Comment by tbille** [comment]
# QA

- add in your `/etc/hosts` file this line: `<K8S_IP> insights.staging.ubuntu.com`
- add in your `/etc/hosts` file this line: `<K8S_IP> insights.ubuntu.com`
- check if you can access the website and all it's awesome features (Insights staging)[http://insights.staging.ubuntu.com/]
- check if you can access the website and all it's awesome features (Insights staging)[http://insights.ubuntu.com/]

**Comment by WillMoggridge** [comment]
Looks good
