### ISSUE TITLE
Go live! Request switch DNS switch for insights.ubuntu.com to K8s

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/insights.ubuntu.com#44]

**Comment by WillMoggridge** [comment]
@nottrobin @anthonydillon 

Worth remembering that the current code points to insights.ubuntu.com and if we change all the traffic to this new site, it will break.

We will likely need to make sure the `/wp-admin`, `/wp-content` and `/wp-json` paths will want to route to the old site.
I think that is all the paths needed?

**Comment by nottrobin** [comment]
Good point @WillMoggridge. Also copying in @tbille - do you think these URLs are all that's needed?

**Comment by anthonydillon** [comment]
There may also be content/assets served. I think we need a while to check
and plan it. Also I think we should get the go ahead from Marketing before
switching.

**Comment by tbille** [comment]
Why don't we separate the 2 services. My opinion is that these are 2 specific services:
- insights: blog
- wordpress: the "content" manager

Couldn't we request a new subdomain?
- insights.ubuntu.com
- wordpress.ubuntu.com

And on the wordpress server we disable the theme and the useless plugins.

**Comment by nottrobin** [comment]
Yeah I do like the sound of that, although it shouldn't be `wordpress.ubuntu.com`. Even now unfortunately, insights is far from the only wordpress installation. It should be something like `admin.insights.ubuntu.com`. In fact (had a quick side-bar with @anthonydillon), I think I'll go ahead and request this be set up now.

**Comment by tbille** [comment]
The problem about moving to this sub-domain `admin.insights.ubuntu.com` is that we keep a strong connexion between insights and wordpress.

The wordpress API is used on differents projects, insights is, in my opinion, at the same level as the others.

But I understand that we have different wordpress instance running.

**Comment by WillMoggridge** [comment]
I'm all for a different subdomain though there is a nagging feeling in the back of my mind about how WordPress handles domains. It has been some times since I had to deal with it.

It may be nothing. Requesting that will help determine any problems.

**Comment by nottrobin** [comment]
@WillMoggridge exactly. The request is in, we'll see what transpires.

**Comment by frankiegranato** [comment]
Will is going to make a new issue on the Vanilla & Base squad board and link it to this one. I won't close this card yet (for the sake of posterity). This card to be moved to Triaged.

**Comment by nottrobin** [comment]
Request filed: [#109218: Point insights.ubuntu.com at prod-comms.kubernetes-ingress.canonical.com](https://portal.admin.canonical.com/109218)

**Comment by frankiegranato** [comment]
I presume this is "done" now. Can we close the issue? @WillMoggridge & @nottrobin

**Comment by nottrobin** [comment]
Done! https://insights.ubuntu.com!
