### ISSUE TITLE
Top/bottom margin of code blocks needs tweaking

### ISSUE THREAD

**Issue by caldav** [canonical-websites/insights.ubuntu.com#5]
The top of code blocks is too close to the previous paragraph.
The bottom is too far from the next paragraph.

Eg. http://0.0.0.0:8023/2017/05/09/ros-production-create-ubuntu-core-image-with-snap-preinstalled-55/

## Screenshots

![screenshot from 2017-10-02 11-49-08](https://user-images.githubusercontent.com/18480003/31072374-ec3d1c4e-a767-11e7-989b-0f4e0f8e5293.png)

---

![screenshot from 2017-10-02 11-50-29](https://user-images.githubusercontent.com/18480003/31072381-f4326526-a767-11e7-99f2-acdf45ceac2d.png)

**Comment by anthonydillon** [comment]
I think this will end up being an issue on Vanilla framework.
