### ISSUE TITLE
Author page is missing - correct image and social links

### ISSUE THREAD

**Issue by caldav** [canonical-websites/insights.ubuntu.com#6]
On profile pages, the "Google +" link is wrong.

# 1 
These links take you to the login.ubuntu.com OpenId Indentity URL of the author (I'm not sure why we would have that available to readers in the first place) 

![screenshot from 2017-10-02 12-07-22](https://user-images.githubusercontent.com/18480003/31072950-46fa32dc-a76a-11e7-9bd5-6d88fbb38d13.png)

-> "Google +" takes you to https://login.ubuntu.com/+id/t3fbsM4

# 2
When the author doesn't have a registered OpenId login for Insights, (eg "Canonical" http://0.0.0.0:8023/author/canonical/ ), the link is still present but the href is not set (so it just takes you to the current page)

_This could be because I'm running a local instance._ The second part of this issue makes me assume the page is looping over a list of links. I'm not sure where the data my local instance is using is coming from and if it's complete (I used the `./run` command). But in any case, there should be no link displayed when there is nothing to loop over and they should have the right label.

**Comment by anthonydillon** [comment]
The template currently has a hardcoded Google+ link. This should be replaced with a loop and look up to output the current links.

**Comment by pmahnke** [comment]
@anthonydillon do you know how to get this from the API?  I have a feeling it is a custom field we have to [enable](https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-rest-api-support-for-custom-content-types/#custom-link-relationships)

**Comment by pmahnke** [comment]
@anthonydillon just to mention, we aren't getting the correct image either, and any of the other social links...

**Comment by anthonydillon** [comment]
After investigation it looks like the wp-json feed does not provide the user contact/extra info. After discussing this with @pmahnke we are happy to move ahead with gravatar images and remove the social icons. If authors would like to link to social networks they can use the author bio.
