### ISSUE TITLE
Is the snappy image the correct one

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/insights.ubuntu.com#74]
Lets ask a designer to check that the logo is the legitimate snappy logo?

**Comment by kwm14** [comment]
@anthonydillon that's an older version of a version of the Snappy logo from 2015.

Looking on the asset manager we have either:

**Full lockup**
https://assets.ubuntu.com/v1/ee62c0fb-snappy-logo.svg

or

**Icon**
https://assets.ubuntu.com/v1/a861450c-snapcraft-logo.svg

Personally in the space given for the image it's probably best to replace with the icon version.

![screen shot 2017-11-28 at 09 35 42](https://user-images.githubusercontent.com/17748020/33312495-fc2e2fb4-d41f-11e7-8043-93a1020fdf4b.png)

**Comment by pmahnke** [comment]
Just to be clear - I think @anthonydillon is talking about the screenshot?

![image](https://user-images.githubusercontent.com/441217/34639043-21c142d8-f2d0-11e7-8019-5f0d90fc0327.png)

I think an app store is better?

**Comment by anthonydillon** [comment]
I do mean the logo as I didn't think snappy had a logo at the time. I believe there is one now though.
