### ISSUE TITLE
Investigate ways to add "preview post" functionality

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#93]
No previewing of posts (in draft)

**Comment by frankiegranato** [comment]
This is not a show-stopper so we could do it at another time - i.e. not iteration 17

**Comment by anthonydillon** [comment]
@frankiegranato Yes this is complicated. So will set the estimate to 13.

**Comment by frankiegranato** [comment]
@steverydz Can you investigate this issue? Not sure how complex/possible this task is!

**Comment by steverydz** [comment]
Pull request: https://github.com/canonical-websites/insights.ubuntu.com/pull/264

**Comment by anthonydillon** [comment]
I'm not sure that PR fixes this issue. This issue is about clicking the preview post button in the admin side.

**Comment by steverydz** [comment]
Gah, I got confused between this and another issue!

**Comment by steverydz** [comment]
From what I can tell from the WordPress API docs it's possible to return posts with a status of draft by appending a query string of `status=draft`. In practice I haven't been able to get this to work with https://admin.insights.ubuntu.com/wp-json/wp/v2/posts?status=draft - I just get a 400.

I think this is likely to be an auth issue, although the auth cookie is sent with the request so not sure why that wouldn't be working?

My thinking is that assuming we can get that endpoint to work, we'd be able to provide a preview by creating a `draft/:post_id` route in the flask app which would serve the single post template.

**Comment by anthonydillon** [comment]
Thanks Steve,

Yes we would need to auth with the API to get draft content. I think this
might be something with pairing with one of the backend developers on.
