### ISSUE TITLE
Drop down menus should be white

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/insights.ubuntu.com#95]
Please can we make the drop down menus white (background)? I think it will make them more visible. See screen shot. ![Ubuntu Insights - menu drop down.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/8f321307-f4ae-4b3e-a573-32e4a90faed7)

**Comment by frankiegranato** [comment]
@anthonydillon can you add an estimate this please? I'd guess something like a 5.

**Comment by anthonydillon** [comment]
Its a small local tweak.
